services:
  postgres-db:
    image: postgres:latest
    container_name: haka-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres2024!
      - POSTGRES_ENCONDING=UTF-8
    ports:
      - 5432:5432
    volumes:
      - ./01-database.sql:/docker-entrypoint-initdb.d/01-database.sql
      - ./datahaka/postgres:/var/lib/postgresql/data
    networks:
      - hakanetwork

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 15432:80
    links:
      - postgres-db
    networks:
      - hakanetwork


  srv-discovery:
    build: './srvDiscovery'
    container_name: srv-discovery
    restart: always
    ports:
      - 8761:8761
    networks:
      - hakanetwork
    depends_on:
      - postgres-db
      - pgadmin
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 5000'

  srv-gateway:
    build: './srvGateway'
    container_name: srv-gateway
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
      - pgadmin
      - srv-discovery
    networks:
      - hakanetwork


  srv-cliente:
    build: './srvCliente'
    container_name: srv-cliente
    restart: always
    ports:
      - 9510:8080
    depends_on:
      - postgres-db
      - pgadmin
      - srv-discovery
      - srv-gateway
    networks:
      - hakanetwork

  srv-cartao:
    build: './srvCartao'
    container_name: srv-cartao
    restart: always
    ports:
      - 9511:8080
    depends_on:
      - postgres-db
      - pgadmin
      - srv-discovery
      - srv-gateway
      - srv-cliente
    networks:
      - hakanetwork

  srv-pagamento:
    build: './srvPagamento'
    container_name: srv-pagamento
    restart: always
    ports:
      - 9512:8080
    depends_on:
      - postgres-db
      - pgadmin
      - srv-discovery
      - srv-gateway
      - srv-cliente
      - srv-cartao
    networks:
      - hakanetwork

networks:
  hakanetwork:
    driver: bridge
