spring:
  application:
    name: SrvAutenticacao
  # Postgresql
  datasource:
    url: jdbc:postgresql://postgres-db:5432/haka
    username: postgres
    password: Postgres2024!

    hikari:
      schema: dbUsuarios
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: dbUsuarios
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: true


# Others
server:
  port: 9513


# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://srv-discovery:8761/eureka

api:
  security:
    token:
      secret: ${JWT_SECRET:batman batman batman}