spring:
  application:
    name: srvCliente
  # Postgresql
  datasource:
    url: jdbc:postgresql://postgres-db:5432/haka
    username: postgres
    password: Postgres2024!

    hikari:
      schema: dbClientes
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: dbClientes
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: true


# Others
server:
  port: 9510

# Swagger
openapi:
  service:
    title: service-cliente doc
    version: 1.0.0
    url: localhost:8080
springdoc:
  api-docs:
    path: /api/cliente/api-docs
  swagger-ui:
    path: /api/cliente/swagger-ui.html

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://srv-discovery:8761/eureka
