spring:
  application:
    name: srvGateway

  cloud:
    gateway:
      routes:
        - id: tbsrvcliente
          uri: lb://srvcliente
          predicates:
            - Path=/api/cliente/**

        - id: tbsrvcartao
          uri: lb://srvcartao
          predicates:
            - Path=/api/cartao/**


server:
  port: 8080

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://srv-discovery:8761/eureka
