spring:
  application:
    name: srvGateway

server:
  port: 8080

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://srv-discovery:8761/eureka

