spring:
  application:
    name: srvCartao
  # Postgresql
  datasource:
#    url: ${SP_DTSRC_URL:jdbc:postgresql://postgres-db:5432/fase5}
#    username: ${SP_DTSRC_USERNAME:postgres}
#    password: ${SP_DTSRC_PASSWORD:Postgres2023!}
    url: ${SP_DTSRC_URL:jdbc:postgresql://localhost:5432/srvCartao}
    username: ${SP_DTSRC_USERNAME:postgres}
    password: ${SP_DTSRC_PASSWORD:Postgres2023!}
    hikari:
      schema: dbcartao
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: dbcartao
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: true

openapi:
  service:
    title: service-cartao doc
    version: 1.0.0
    url: localhost:8080
springdoc:
  api-docs:
    path: /cartao/api-docs
  swagger-ui:
    path: /cartao/swagger-ui.html

# Eureka
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUR_DEFAULTZONE:http://srv-discovery:8761/eureka}

# Others
server:
  port: 9511
